version: '3.3'

networks:
  servicebus:

services:
  tests:
    image: node
    volumes:
      - .:/usr/src/
    working_dir: /usr/src/
    user: root
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - servicebus
    command: npm run test:execute

  rabbitmq:
    image: rabbitmq:3.8-management
    networks:
      - servicebus
    ports:
      - 5672:5672

  redis:
    image: redis
    networks:
      - servicebus
    ports:
      - 6379:6379